# Generated by Django 5.2.4 on 2025-08-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_questobjective_experience_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questobjective',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='questobjective',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
